import numpy as np
#a = np.arange(10)
#print(a)
#a = np.arange(10.0)
#print(a)
#a = np.arange(3, 10)
#print(a)
#a = np.arange(-5, 6)
#print(a)
#a = np.arange(4, 11, dtype = "float")
#print(a)
#a = np.arange(4, 11, dtype = "complex")
#print(a)
#a = np.arange(1, 11, 2)
#print(a)
a = np.arange(1, 11, 5)
print(a)
