import numpy as np

#a =  np.array([1, 2, 3, 4, 5])
#print(a.dtype)
#a =  np.array([1, 2, 3, 4, 5],dtype = "int")
#print(a.dtype)
#a =  np.array([1, 2, 3, 4, 5],dtype = "float")
#print(a)
#print(a.dtype)
#a =  np.array([1, 2, 3, 4, 5],dtype = "complex")
#print(a)
#print(a.dtype)
a =  np.array([[1, 2, 3],[4, 5, 6]],dtype = "float")
print(a)
print(a.dtype)